### ISSUE TITLE
Disabler.js not recognized

### ISSUE THREAD

**Issue by LinuxSushi** [Rilshrink/Minecraft-Disablers#7]
FDP version: 2.0.0
Core.lib *is present*

The disabler simply does not work / appear in FDP.

**Comment by Rilshrink** [comment]
I no longer work on this project, but if you could possibly provide error logs I could attempt to fix the issue.

**Comment by FluteVegeables** [comment]
You need to change it to API version 2, the old one doesn't work

**Comment by f4r2** [comment]
> FDP version: 2.0.0 Core.lib _is present_
> 
> The disabler simply does not work / appear in FDP.

Bro fdp dont work with core.lib its using old script api
